version: 0.2

env:
  variables:
    CONFIGURATION: "Release"
    PUBLISH_DIR: "output"
    DOTNET_VERSION: "8.0.405"

phases:
  install:
    commands:
      - Write-Host "Downloading dotnet-install script..."
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile dotnet-install.ps1"
      - Write-Host "Installing .NET SDK..."
      - powershell -NoProfile -ExecutionPolicy Bypass -File .\dotnet-install.ps1 -Version $env:DOTNET_VERSION -InstallDir C:\dotnet
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "$env:PATH = 'C:\dotnet;' + $env:PATH"
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "C:\dotnet\dotnet.exe --info"
      - Write-Host "Restoring packages..."
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "C:\dotnet\dotnet.exe restore"

  build:
    commands:
      - Write-Host "Building project..."
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "C:\dotnet\dotnet.exe build -c $env:CONFIGURATION --no-restore"

  post_build:
    commands:
      - Write-Host "Publishing project..."
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& {
          $pubRoot = Join-Path (Get-Location) $env:PUBLISH_DIR
          if (-not (Test-Path $pubRoot)) { New-Item -ItemType Directory -Path $pubRoot | Out-Null }
          Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
            if (Select-String -Path $_.FullName -Pattern 'Microsoft.NET.Sdk.Web' -Quiet) {
              Write-Host 'Publishing' $_.FullName
              C:\dotnet\dotnet.exe publish $_.FullName -c $env:CONFIGURATION -o $pubRoot
            }
          }
        }"

      - Write-Host "Preparing CodeDeploy bundle (artifact.zip)..."
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& {
          $dist = Join-Path (Get-Location) 'dist'
          if (Test-Path $dist) { Remove-Item -Recurse -Force $dist }
          New-Item -ItemType Directory -Path (Join-Path $dist 'app') | Out-Null

          # copy publish output
          $pubRoot = Join-Path (Get-Location) $env:PUBLISH_DIR
          Copy-Item -Path (Join-Path $pubRoot '*') -Destination (Join-Path $dist 'app') -Recurse -Force

          # copy appspec.yml
          if (Test-Path 'appspec.yml') {
            Copy-Item 'appspec.yml' -Destination $dist -Force
          }

          # copy scripts
          if (Test-Path 'scripts') {
            New-Item -ItemType Directory -Path (Join-Path $dist 'scripts') -Force | Out-Null
            Copy-Item 'scripts\*' -Destination (Join-Path $dist 'scripts') -Recurse -Force
          }

          # create artifact.zip
          if (Test-Path 'artifact.zip') { Remove-Item 'artifact.zip' -Force }
          Compress-Archive -Path (Join-Path $dist '*') -DestinationPath 'artifact.zip' -Force
        }"

artifacts:
  files:
    - artifact.zip
