version: 0.2

env:
  variables:
    CONFIGURATION: "Release"
    PUBLISH_DIR: "output"
    DOTNET_VERSION: "8.0.405"

phases:
  install:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile dotnet-install.ps1"
      - powershell -NoProfile -ExecutionPolicy Bypass -File .\dotnet-install.ps1 -Version $env:DOTNET_VERSION -InstallDir C:\dotnet
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' --info"

  pre_build:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' restore"

  build:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' build -c $env:CONFIGURATION --no-restore"

  post_build:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& { 
          $builtPath = Join-Path (Get-Location) 'pipe\\pipe\\bin\\Release\\net8.0';
          $pubRoot = Join-Path (Get-Location) $env:PUBLISH_DIR;
          if (-not (Test-Path $pubRoot)) { New-Item -ItemType Directory -Force -Path $pubRoot | Out-Null }
          if (Test-Path $builtPath) {
            if (Test-Path (Join-Path $pubRoot 'app')) { Remove-Item -Recurse -Force (Join-Path $pubRoot 'app') -ErrorAction SilentlyContinue }
            New-Item -ItemType Directory -Force -Path (Join-Path $pubRoot 'app') | Out-Null
            Copy-Item -Path (Join-Path $builtPath '*') -Destination (Join-Path $pubRoot 'app') -Recurse -Force
            Write-Host 'Copied build output from' $builtPath 'to' (Join-Path $pubRoot 'app')
          } else {
            Write-Host 'Built path not found:' $builtPath
          }
          $dist = Join-Path (Get-Location) 'dist';
          if (Test-Path $dist) { Remove-Item -Recurse -Force $dist -ErrorAction SilentlyContinue }
          New-Item -ItemType Directory -Force -Path (Join-Path $dist 'app') | Out-Null
          if (Test-Path $pubRoot) { Copy-Item -Path (Join-Path $pubRoot '*') -Destination (Join-Path $dist 'app') -Recurse -Force; Write-Host 'Copied publish output to' (Join-Path $dist 'app') } else { Write-Host 'Publish root not found:' $pubRoot }
          if (Test-Path 'appspec.yml') { Copy-Item -Path 'appspec.yml' -Destination $dist -Force; Write-Host 'Copied appspec.yml to' $dist }
          if (Test-Path 'scripts') { Copy-Item -Path 'scripts\\*' -Destination (Join-Path $dist 'scripts') -Recurse -Force; Write-Host 'Copied scripts to' (Join-Path $dist 'scripts') }
          if (Test-Path 'artifact.zip') { Remove-Item 'artifact.zip' -Force }
          Compress-Archive -Path (Join-Path $dist 'app\\*') -DestinationPath 'artifact.zip' -Force
          Write-Host 'artifact.zip created at' (Join-Path (Get-Location) 'artifact.zip')
        }"

artifacts:
  files:
    - artifact.zip
