version: 0.2

env:
  variables:
    CONFIGURATION: "Release"
    PUBLISH_DIR: "output"
    DOTNET_VERSION: "8.0.405"

phases:
  install:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile dotnet-install.ps1"
      - powershell -NoProfile -ExecutionPolicy Bypass -File .\dotnet-install.ps1 -Version $env:DOTNET_VERSION -InstallDir C:\dotnet
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' --info"

  pre_build:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' restore"

  build:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' build -c $env:CONFIGURATION --no-restore"

  post_build:
    # Keep each command as a single YAML list item. Avoid $vars and multi-line scripts.
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "if (-not (Test-Path 'output\\app')) { New-Item -ItemType Directory -Path 'output\\app' | Out-Null }"
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "Copy-Item -Path 'pipe\\pipe\\bin\\Release\\net8.0\\*' -Destination 'output\\app' -Recurse -Force"
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "if (Test-Path 'dist') { Remove-Item -Recurse -Force 'dist' -ErrorAction SilentlyContinue }; New-Item -ItemType Directory -Path 'dist\\app' | Out-Null"
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "Copy-Item -Path 'output\\*' -Destination 'dist\\app' -Recurse -Force"
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "if (Test-Path 'artifact.zip') { Remove-Item 'artifact.zip' -Force }; Compress-Archive -Path 'dist\\app\\*' -DestinationPath 'artifact.zip' -Force; Write-Host 'artifact.zip created.'"

artifacts:
  files:
    - artifact.zip
