version: 0.2

env:
  variables:
    DOTNET_VERSION: "8.0.405"
    CONFIGURATION: "Release"

phases:
  install:
    commands:
      - Write-Host "Downloading dotnet-install..."
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile dotnet-install.ps1"
      - powershell -NoProfile -ExecutionPolicy Bypass -File .\dotnet-install.ps1 -Version $env:DOTNET_VERSION -InstallDir C:\dotnet
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' --info"

  pre_build:
    commands:
      - Write-Host "Restoring packages..."
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' restore"

  build:
    commands:
      - Write-Host "Building..."
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' build -c $env:CONFIGURATION --no-restore"

  post_build:
    commands:
      - Write-Host "Prepare app folder..."
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "if (Test-Path 'app') { Remove-Item -Recurse -Force 'app' }"
      - Write-Host "Publish project into top-level app folder..."
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' publish 'pipe\\pipe\\pipe.csproj' -c $env:CONFIGURATION -o 'app'"
      - Write-Host "Create artifact.zip with app, appspec.yml and scripts (if present)..."
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "if (Test-Path 'artifact.zip') { Remove-Item -Force 'artifact.zip' -ErrorAction SilentlyContinue }; $paths=@(); if (Test-Path 'app') { $paths += 'app' }; if (Test-Path 'appspec.yml') { $paths += 'appspec.yml' }; if (Test-Path 'scripts') { $paths += 'scripts' }; if ($paths.Count -eq 0) { Write-Host 'Nothing to archive'; exit 1 } ; Compress-Archive -Path $paths -DestinationPath 'artifact.zip' -Force; Write-Host 'artifact.zip created.'"

artifacts:
  files:
    - artifact.zip
  discard-paths: yes
