version: 0.2

env:
  variables:
    CONFIGURATION: "Release"
    PUBLISH_DIR: "output"
    DOTNET_VERSION: "8.0.405"

phases:
  install:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile dotnet-install.ps1"
      - powershell -NoProfile -ExecutionPolicy Bypass -File .\dotnet-install.ps1 -Version $env:DOTNET_VERSION -InstallDir C:\dotnet
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' --info"

  pre_build:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' restore"

  build:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' build -c $env:CONFIGURATION --no-restore"

  post_build:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command '
          $dll = Get-ChildItem -Path . -Recurse -Filter "*.dll" -File | Where-Object { $_.FullName -match "\\\\bin\\\\Release\\\\" } | Select-Object -First 1;
          if ($null -eq $dll) { Write-Host "ERROR: no built dll found under any bin\\Release folder"; exit 1 }
          $builtDir = Split-Path $dll.FullName -Parent;
          Write-Host "Found build directory: $builtDir";
          $dest = "output\\app";
          if (-not (Test-Path $dest)) { New-Item -ItemType Directory -Path $dest | Out-Null }
          Copy-Item -Path (Join-Path $builtDir "*") -Destination $dest -Recurse -Force;
          $dist = "dist";
          if (Test-Path $dist) { Remove-Item -Recurse -Force $dist -ErrorAction SilentlyContinue }
          New-Item -ItemType Directory -Path (Join-Path $dist "app") | Out-Null;
          Copy-Item -Path (Join-Path $dest "*") -Destination (Join-Path $dist "app") -Recurse -Force;
          if (Test-Path "artifact.zip") { Remove-Item "artifact.zip" -Force };
          Compress-Archive -Path (Join-Path $dist "app\\*") -DestinationPath "artifact.zip" -Force;
          Write-Host "artifact.zip created at" (Join-Path (Get-Location) "artifact.zip");
        '

artifacts:
  files:
    - artifact.zip
