version: 0.2

env:
  variables:
    CONFIGURATION: "Release"
    PUBLISH_DIR: "output"
    DOTNET_VERSION: "8.0.405"

phases:
  install:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile dotnet-install.ps1"
      - powershell -NoProfile -ExecutionPolicy Bypass -File .\dotnet-install.ps1 -Version $env:DOTNET_VERSION -InstallDir C:\dotnet
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' --info"

  pre_build:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' restore"

  build:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' build -c $env:CONFIGURATION --no-restore"

  post_build:
    commands:
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "& 'C:\dotnet\dotnet.exe' publish 'pipe\\pipe\\pipe.csproj' -c $env:CONFIGURATION -o 'output\\pipe' ; if (-not (Test-Path 'dist')) { New-Item -ItemType Directory -Path 'dist' | Out-Null } ; if (-not (Test-Path 'dist\\app')) { New-Item -ItemType Directory -Path 'dist\\app' | Out-Null } ; if (Test-Path 'output') { Copy-Item -Path 'output\\*' -Destination 'dist\\app' -Recurse -Force } ; if (Test-Path 'artifact.zip') { Remove-Item 'artifact.zip' -Force } ; Compress-Archive -Path 'dist\\*' -DestinationPath 'artifact.zip' -Force ; Write-Host 'artifact.zip created.'"

artifacts:
  files:
    - artifact.zip
