version: 0.2

env:
  variables:
    CONFIGURATION: "Release"
    PUBLISH_DIR: "output"
    DOTNET_VERSION: "8.0.405"

phases:
  install:
    commands:
      - echo "=== Downloading dotnet-install script ==="
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest 'https://dot.net/v1/dotnet-install.ps1' -OutFile dotnet-install.ps1"

      - echo "=== Installing .NET SDK $env:DOTNET_VERSION ==="
      - powershell -NoProfile -ExecutionPolicy Bypass -Command ".\dotnet-install.ps1 -Version $env:DOTNET_VERSION -InstallDir C:\dotnet"

      - echo "=== Updating PATH ==="
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "$env:PATH = 'C:\dotnet;' + $env:PATH"

      - echo "=== .NET Info ==="
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "C:\dotnet\dotnet.exe --info"

      - echo "=== Restoring NuGet packages ==="
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "C:\dotnet\dotnet.exe restore"

  build:
    commands:
      - echo "=== Building Project(s) ==="
      - powershell -NoProfile -ExecutionPolicy Bypass -Command "C:\dotnet\dotnet.exe build -c $env:CONFIGURATION --no-restore"

  post_build:
    commands:
      - echo "=== Publishing Web Projects ==="
      - powershell -NoProfile -ExecutionPolicy Bypass -Command ^
          "$pub = Join-Path (Get-Location) $env:PUBLISH_DIR; ^
           New-Item -ItemType Directory -Force -Path $pub | Out-Null; ^
           Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object { ^
             if (Select-String -Path $_.FullName -Pattern 'Microsoft.NET.Sdk.Web' -Quiet) { ^
               Write-Host 'Publishing' $_.FullName; ^
               & 'C:\dotnet\dotnet.exe' publish $_.FullName -c $env:CONFIGURATION -o (Join-Path $pub $_.BaseName); ^
             } ^
           }"

      - echo "=== Preparing CodeDeploy artifact.zip ==="
      - powershell -NoProfile -ExecutionPolicy Bypass -Command ^
          "$dist = Join-Path (Get-Location) 'dist'; ^
           Remove-Item -Recurse -Force -ErrorAction SilentlyContinue $dist; ^
           New-Item -ItemType Directory -Force -Path (Join-Path $dist 'app') | Out-Null; ^
           # copy published output
           Get-ChildItem -Path $env:PUBLISH_DIR -Directory | ForEach-Object { ^
             $dest = Join-Path (Join-Path $dist 'app') $_.Name; ^
             Write-Host 'Copying folder' $_.FullName 'to' $dest; ^
             Copy-Item -Path $_.FullName\* -Destination $dest -Recurse -Force; ^
           }; ^
           # copy appspec.yml
           Copy-Item -Path 'appspec.yml' -Destination $dist -Force; ^
           # copy scripts folder
           New-Item -ItemType Directory -Force -Path (Join-Path $dist 'scripts') | Out-Null; ^
           Copy-Item -Path 'scripts\*' -Destination (Join-Path $dist 'scripts') -Recurse -Force; ^
           # create artifact.zip
           if (Test-Path 'artifact.zip') { Remove-Item 'artifact.zip' -Force }; ^
           Compress-Archive -Path (Join-Path $dist '*') -DestinationPath 'artifact.zip' -Force; ^
           Write-Host 'artifact.zip created.'"

artifacts:
  files:
    - artifact.zip
